msm: mdss: add missing argument
This fixes the compile error due to commit 56fbdf8276c001022e9d8a456db772d6b85ec101.

drivers/video/msm/mdss/mdss_dsi_panel.c: In function 'mdss_dsi_panel_set_param':
drivers/video/msm/mdss/mdss_dsi_panel.c:290:2: error: too few arguments to function 'mdss_dsi_panel_cmds_send'
  mdss_dsi_panel_cmds_send(ctrl, &cmds[val]);
  ^
drivers/video/msm/mdss/mdss_dsi_panel.c:200:13: note: declared here
 static void mdss_dsi_panel_cmds_send(struct mdss_dsi_ctrl_pdata *ctrl,

Picked from https://github.com/MotorolaMobilityLLC/kernel-msm/commit/abbd1b205e8b0cfea2a8b16b2e433bf51d91bfc6

Signed-off-by: Rohit Vashisht <rohitv88cf@gmail.com>